In [2]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [15]:
np.zeros(9, int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
np.zeros((3, 3),int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
np.ones((2, 3), int)

array([[1, 1, 1],
       [1, 1, 1]])

In [25]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.random.rand(5)

array([0.88816527, 0.62191014, 0.26525686, 0.62129742, 0.70490341])

In [32]:
np.random.randn(3)

array([-1.53636034,  1.19569922, -0.22235893])

In [34]:
np.random.randint(0,10,7)

array([0, 1, 4, 3, 2, 8, 1])

In [35]:
rand_arr = np.random.randint(0, 50, 20)

In [36]:
rand_arr

array([ 2,  1, 16, 21, 38, 21, 39,  6,  8, 45, 31,  8,  8, 34, 13, 32, 24,
       46, 14,  9])

In [38]:
second_arr = np.arange(20)
second_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
rand_arr.reshape(4,5)

array([[ 2,  1, 16, 21, 38],
       [21, 39,  6,  8, 45],
       [31,  8,  8, 34, 13],
       [32, 24, 46, 14,  9]])

In [42]:
second_arr.min()

0

In [43]:
second_arr.max()

19

In [44]:
rand_arr.max()

46

In [45]:
rand_arr.argmax()

17

In [47]:
rand_arr.min()

1

In [48]:
rand_arr.argmin()

1

In [50]:
second_arr.reshape(2,10).shape

(2, 10)

In [51]:
second_arr.dtype

dtype('int64')

In [53]:
np.array((0,1,2,3,4,5,6,7,8,9))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [56]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [57]:
np.ones((5, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [58]:
np.linspace(3,7,5)

array([3., 4., 5., 6., 7.])

In [59]:
np.linspace(3,7,9).reshape(3,3)

array([[3. , 3.5, 4. ],
       [4.5, 5. , 5.5],
       [6. , 6.5, 7. ]])

In [65]:
max_number = np.random.randint(0, 101, 10).max()
print(max_number)

92


# Next one

In [73]:
int_arr = np.random.randint(0, 10, 10)

In [74]:
new_arr = int_arr.copy()

In [75]:
int_arr[-1]

5

In [76]:
int_arr[1:3]

array([4, 1])

In [77]:
int_arr[4:] = 10
int_arr

array([ 8,  4,  1,  6, 10, 10, 10, 10, 10, 10])

In [78]:
new_arr

array([8, 4, 1, 6, 8, 8, 8, 0, 4, 5])

In [79]:
int_arr > 2

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True])

In [80]:
bool_arr = int_arr > 2

In [81]:
int_arr[bool_arr]

array([ 8,  4,  6, 10, 10, 10, 10, 10, 10])

In [82]:
int_arr[int_arr > 2]

array([ 8,  4,  6, 10, 10, 10, 10, 10, 10])

In [83]:
int_arr[int_arr<5]

array([4, 1])

## SERTIFICATED!!!

In [85]:
two_dim_arr = np.arange(12).reshape(3,4)

In [86]:
two_dim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
two_dim_arr[2][1]

9

In [89]:
two_dim_arr[2,1]

9

In [90]:
two_dim_arr[0:2,0:2]

array([[0, 1],
       [4, 5]])

In [91]:
two_dim_arr[:2,2:]

array([[2, 3],
       [6, 7]])

In [93]:
two_dim_arr[two_dim_arr>4]

array([ 5,  6,  7,  8,  9, 10, 11])

In [98]:
first_arr = np.random.randint(1,20,10)
slice_arr = first_arr[1:6]
print(f'{first_arr}\n{slice_arr}')

[14  5  7  8 12 14 11 14 16  4]
[ 5  7  8 12 14]


In [100]:
second_arr = np.random.randint(0,20,10)
slice_arr = first_arr[2:]
print(f'{second_arr}\n{slice_arr}')

[ 3  7  8  2 14  1  5 12  8  9]
[14  3  9 12 10  7  1  4]


In [113]:
third_arr = np.random.randint(3,12,12).reshape(4,3)
slice_arr = third_arr[1:3,:2]
print(f'{third_arr}\n\n{slice_arr}')

[[ 8  5  8]
 [11 10  8]
 [10  4 11]
 [ 3 10  9]]

[[11 10]
 [10  4]]


In [119]:
fourth_arr = np.random.randint(0,10,24).reshape(4,6)
slice_arr = fourth_arr[fourth_arr > 3]
print(f'{fourth_arr}\n\n{slice_arr}')

[[3 1 7 7 6 9]
 [8 5 7 7 6 9]
 [5 4 1 7 7 1]
 [1 7 7 8 8 4]]

[7 7 6 9 8 5 7 7 6 9 5 4 7 7 7 7 8 8 4]


# Next

In [126]:
arr = np.arange(0, 11)

In [122]:
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [123]:
arr + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [124]:
arr * 100

array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [127]:
arr / 0

<ipython-input-127-db39a1c38901>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr / 0
<ipython-input-127-db39a1c38901>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / 0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [128]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [129]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [130]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [131]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])